# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('estudios', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=100)),
                ('sitioWeb', models.CharField(max_length=100)),
                ('oficina', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('grupoInvestigacion', models.CharField(max_length=100)),
            ],
        ),
    ]
