# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-05 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddv_example', '0003_auto_20170304_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='id',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
