# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddv_example', '0005_profesor_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
