# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-05 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddv_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='correo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='estudios',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='extension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='grupoInvestigacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='oficina',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='sitioWeb',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
